module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'books',
      [
        {
          id: 1,
          isbn: '9788573517941',
          title: 'Batman - Ano Um',
          edition: null,
          pages: 152,
          description: `Bruce Wayne e James Gordon chegam
            \u00e0 Gotham ao mesmo tempo, com miss\u00f5es diferentes.
            Gordon junta-se \u00e0 pol\u00edcia da cidade, descobrindo logo que ela
            \u00e9 corrupta. Wayne, disfar\u00e7ado de vagabundo, testa seus anos de
            treinamento em uma simples briga de rua na Zona Leste, que n\u00e3o sai como
            ele planejou: ele acaba baleado. Ferido e em busca de inspira\u00e7\u00e3o,
            ele tem uma ideia quando v\u00ea um morcego voando pela janela.`,
          publishing_date: new Date('2011-08-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '37.00',
          thumbnail: 'static/covers/978-8573517941.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          isbn: '8573516976',
          title: 'One Piece',
          edition: '1',
          pages: 212,
          description: `Luffy \u00e9 um garoto que deseja tornar-se
            um pirata por causa do Shanks. Durante uma discuss\u00e3o
            com Shanks por causa de alguns bandidos das montanhas, o garoto acaba
            comendo a Gomu Gomu no Mi. Mais tarde, por\u00e9m, os bandidos retornam e
            Luffy decide comprar briga com eles bem quando os piratas n\u00e3o est\u00e3o
            l\u00e1 para proteg\u00ea-lo. Shanks salva Luffy, mas acaba perdendo seu bra\u00e7o
            esquerdo por conta disso e logo deixa seu chap\u00e9u com o garoto.`,
          publishing_date: new Date('2012-02-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/8573516976.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          isbn: '9788573516531',
          title: 'Sandman',
          edition: '1',
          pages: 618,
          description:
            'Londres, 1916. John Hathaway, curador do museu real, ao perder o filho na 1\u00aa Guerra Mundial, se rende \u00e0s investidas do ardiloso Roderick Burgess, o "Rei-Dem\u00f4nio", um m\u00edstico, l\u00edder da seita chamada "A Ordem". \nHathaway lhe entrega um livro que permitir\u00e1 a Burgess realizar seu maior feito: capturar a Morte em pessoa. \nMas algo sai errado e ele pega Morpheus, o Senhor dos Sonhos. Enquanto Burgess envelhece amargurado e o mundo vive uma estranha doen\u00e7a do sono, Morpheus prepara sua fuga e vingan\u00e7a',
          publishing_date: new Date('2010-04-01'),
          format: '(19 x 28 cm)\nColorido/Capa dura',
          price: '145.00',
          thumbnail: 'static/covers/978-8573516531.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          isbn: '9788583681403',
          title: 'V de vingan\u00e7a',
          edition: null,
          pages: 308,
          description:
            'Numa Inglaterra dominada por um regime totalit\u00e1rio, uma figura misteriosa chamada simplesmente V, usando vestimentas e uma m\u00e1scara que evocam a imagem de um infame personagem hist\u00f3rico brit\u00e2nico, desponta no horizonte como a \u00fanica chance de que haja liberdade novamente.',
          publishing_date: new Date('2012-05-01'),
          format: '(17 x 26 cm)\nColorido/Lombada quadrada',
          price: '24.90',
          thumbnail: 'static/covers/978-8583681403.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          isbn: '8573518847',
          title: 'One Piece',
          edition: '2',
          pages: 204,
          description:
            'Luffy conhece a Nami, os dois conversam um pouco e descobrem que ambos pretendem ir para a Grand Line. Luffy pergunta se ela quer se juntar a ele como navegadora de seu bando pirata para irem \u00e0 Grand Line, mas ao saber que Luffy era um pirata, ela se nega a trabalhar junto com ele. A garota ent\u00e3o decide entregar Luffy para Buggy e o amarra. O pirata, que est\u00e1 dominando a vila, mostra possuir o poder de uma Akuma no Mi e fica bastante surpreso ao saber que Nami estava vindo ao seu encontro.',
          publishing_date: new Date('2012-03-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/8573518847.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          isbn: '9788573518931',
          title: 'One Piece',
          edition: '3',
          pages: 204,
          description:
            'Buggy admite conhecer Shanks, mas n\u00e3o est\u00e1 disposto a contar nada do que sabe a Luffy. Os dois come\u00e7am a lutar utilizando seus poderes adquiridos pela Akuma no mi, tornando a luta bem equilibrada. Por\u00e9m, Luffy \u00e9 surpreendido por Buggy, que o acerta, atingindo ainda seu t\u00e3o precioso chap\u00e9u de palha. Ao perceber a raiva de Luffy por ter seu tesouro atingido, o palha\u00e7o volta a mirar contra ela e o perfura. Luffy avan\u00e7a furioso para cima de Buggy, que descobre que aquele chap\u00e9u pertencia a Shanks.',
          publishing_date: new Date('2012-04-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/9788573518931.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          isbn: '9788573515473',
          title: 'Batman - A Piada Mortal',
          edition: null,
          pages: 88,
          description:
            'Um dia ruim. \u00c9 apenas isso que separa o homem s\u00e3o da loucura. Pelo menos segundo o Coringa, um dos maiores e mais conhecidos vil\u00f5es dos quadrinhos. E ele quer provar seu ponto de vista enlouquecendo ningu\u00e9m menos que o maior aliado de seu grande inimigo: o Comiss\u00e1rio Gordon. Cabe ao Cavaleiro das Trevas impedi-lo.',
          publishing_date: new Date('2011-10-01'),
          format: '(17 x 26 cm)\nColorido/Capa dura',
          price: '19.90',
          thumbnail: 'static/covers/978-8573515473.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 8,
          isbn: '9788573519037',
          title: 'One Piece',
          edition: '4',
          pages: 196,
          description:
            'As pessoas da vila n\u00e3o acreditam em Usopp e o perseguem. Enquanto isso, Zoro e companhia acham Luffy na praia e ele explica toda a situa\u00e7\u00e3o. Usopp invade a mans\u00e3o e tenta convencer Kaya de que Klahador \u00e9 na verdade o Capit\u00e3o Kuro. Ela n\u00e3o acredita nele e d\u00e1 um tapa em seu rosto. Merry chega ao local e acaba acertando um tiro no bra\u00e7o do garoto, que fica desesperado com ningu\u00e9m acreditar no que ele diz. Mais tarde, ele mente para Piiman, Ninjin e Tamanegi dizendo que inventou tudo sobre Kuro.',
          publishing_date: new Date('2012-05-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/9788573519037.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 9,
          isbn: '9788573519105',
          title: 'One Piece',
          edition: '5',
          pages: 196,
          description:
            'Fugindo pela floresta, os piratas de Usopp correm com Kaya para se protegerem de Jango, que consegue destruir v\u00e1rias \u00e1rvores com seu chackram. Na ladeira, todos ouvem o barulho que vem da floresta e ficam apreensivos. Usopp mal consegue se mover e os piratas de Jango come\u00e7am a rir do atirador. Luffy se enfurece e os ataca, perguntando qual \u00e9 a gra\u00e7a naquilo. Zoro derrota facilmente Buchi e carrega Usopp nas costas como guia e parte para a floresta. Luffy e Kuro come\u00e7am a se enfrentar para valer.',
          publishing_date: new Date('2012-06-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/9788573519105.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 10,
          isbn: '9788565484015',
          title: 'Batman - O Filho do Dem\u00f4nio',
          edition: null,
          pages: 96,
          description:
            'Batman \u00e9 obrigado a se aliar ao seu maior advers\u00e1rio para deter um terrorista sanguin\u00e1rio e insano que obt\u00e9m o controle de uma m\u00e1quina capaz de manipular o clima. Assim, o Cruzado Encapuzado se v\u00ea em uma dif\u00edcil situa\u00e7\u00e3o, tendo de ca\u00e7ar o s\u00e1dico criminoso e, ao mesmo tempo, proteger Talia, a mulher que pode estar carregando em seu ventre o filho do Homem-Morcego.',
          publishing_date: new Date('2012-09-01'),
          format: '(21 x 28 cm)\nColorido/Capa dura',
          price: '17.90',
          thumbnail: 'static/covers/978-8565484015.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 11,
          isbn: '9788573519259',
          title: 'One Piece',
          edition: '6',
          pages: 196,
          description:
            'Luffy v\u00ea atitude de compaix\u00e3o de Sanji ao dar comida a Gin e pede para ele se tornar seu cozinheiro, mas Sanji recusa. Gin fala que Luffy deve desistir de ir \u00e0 Grand Line, pois l\u00e1 \u00e9 muito perigoso. Zeff aparece enquanto Gin est\u00e1 para partir e se desculpa por dar trabalho ao cozinheiro. Enquanto isso, dentro do restaurante, os demais cozinheiros ficam discutindo sobre Don Krieg. Luffy volta ao restaurante para trabalhar, mas n\u00e3o consegue fazer nada direito, ouvindo reclama\u00e7\u00f5es de todos os lados',
          publishing_date: new Date('2012-07-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 12,
          isbn: '9788565484497',
          title: 'Superman - O Que Aconteceu Ao Homem de A\u00e7o?',
          edition: null,
          pages: 132,
          description:
            'Lois Lane Elliott, agora casada, m\u00e3e e uma feliz dona de casa, recebe um rep\u00f3rter do Planeta Di\u00e1rio e relembra os acontecimentos de dez anos antes, quando o mundo viu o Superman pela \u00faltima vez e este teve sua maior e derradeira aventura. Cl\u00e1ssica aventura que serviu de despedida para o Superman Pr\u00e9-Crise (1938-1985) e para o lend\u00e1rio editor Julius Schwartz, \u00edcone da Era de Prata dos Quadrinhos.',
          publishing_date: new Date('2013-07-01'),
          format: '(17 x 26 cm)\nColorido/Capa dura',
          price: '19.90',
          thumbnail: 'static/covers/978-8565484497.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 13,
          isbn: '9788535906288',
          title: 'Maus',
          edition: null,
          pages: 300,
          description:
            'O trecho final da hist\u00f3ria do pai de Art \u00e9 contada at\u00e9 o final da guerra. O trabalho metaling\u00fc\u00edstico assume propor\u00e7\u00f5es \u00fanicas nesta segunda parte.\nTraduzido para mais de dezoito l\u00ednguas, MAUS foi a \u00fanica hist\u00f3ria em quadrinhos a ganhar o Pr\u00eamio Pulitzer.',
          publishing_date: new Date('2005-06-01'),
          format: '(16 x 23 cm)\nColorido/Preto e branco/Lombada quadrada',
          price: '39.00',
          thumbnail: 'static/covers/978-8535906288.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 14,
          isbn: '9788573519402',
          title: 'One Piece',
          edition: '8',
          pages: 196,
          description:
            'O g\u00e1s t\u00f3xico do MH5 tem como principal v\u00edtima Gin, \u00fanico a sofrer todo o ataque sem uma m\u00e1scara. Luffy parte para cima de Don Krieg com tudo, que volta a disparar dardos contra ele. Sem se importar, o garoto enfim se aproxima de Don Krieg, que usa um manto de espinhos para se proteger. Mesmo assim, Luffy n\u00e3o se importa e desfere um poderoso soco no oponente, atingindo os espinhos no processo. Zeff manda Sanji prestar aten\u00e7\u00e3o na luta de Luffy e perceber sua determina\u00e7\u00e3o.',
          publishing_date: new Date('2012-09-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/9788573519402.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 15,
          isbn: '9781401220839',
          title: 'Saga do Monstro do P\u00e2ntano',
          edition: '1',
          pages: 212,
          description:
            'Ap\u00f3s a \u00faltima batalha contra seu inimigo Arcane, o Monstro do P\u00e2ntano se separa de seus amigos Abby e Matt Cable, Liz Tremayne e Dennis Barclay para se certificar que o vil\u00e3o morreu na queda de sua aeronave. Contudo, o que o her\u00f3i pantanoso nem desconfia \u00e9 que a tem\u00edvel organiza\u00e7\u00e3o Sunderland est\u00e1 em seu encal\u00e7o e est\u00e1 disposta a tudo para captur\u00e1-lo, vivo ou morto',
          publishing_date: new Date('2014-04-01'),
          format: '(17 x 26 cm)\nColorido/Lombada quadrada',
          price: '23.90',
          thumbnail: 'static/covers/978-1401220839.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 16,
          isbn: '9788565484343',
          title: 'Batman - O Que Aconteceu Ao Cavaleiro das Trevas?',
          edition: null,
          pages: 132,
          description:
            'Ele \u00e9 o protetor de Gotham City, o esp\u00edrito vingador da cidade, seu Cavaleiro das Trevas. \nPor anos, ele travou sua guerra de um homem s\u00f3 para manter as ruas seguras, mas, esta noite, a guerra causou sua \u00faltima e maior baixa - o pr\u00f3prio Batman. \nO Cruzado Encapuzado agora descansa em um caix\u00e3o no Beco do Crime, o lugar onde nasceu. \nSeus amigos mais pr\u00f3ximos e seus inimigos mais mortais se re\u00fanem para prestar uma \u00faltima homenagem.',
          publishing_date: new Date('2013-04-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '21.90',
          thumbnail: 'static/covers/978-8565484343.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 17,
          isbn: '9788573516906',
          title: 'Guerra Civil',
          edition: null,
          pages: 214,
          description:
            'A a\u00e7\u00e3o precipitada de um grupo de jovens super-her\u00f3is acarreta uma trag\u00e9dia sem precedentes, deixando um saldo de centenas de mortos. Diante da press\u00e3o popular, o governo sanciona uma lei determinando que todos os superseres sejam registrados. A iniciativa divide a comunidade heroica como nunca antes. De um lado, a fac\u00e7\u00e3o pr\u00f3-registro, liderada pelo Homem de Ferro; do outro, os contr\u00e1rios \u00e0 medida, tendo \u00e0 frente o Capit\u00e3o Am\u00e9rica.',
          publishing_date: new Date('2010-08-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '58.00',
          thumbnail: 'static/covers/978-8573516906.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 18,
          isbn: '789765352158602',
          title: 'Saga do Monstro do P\u00e2ntano',
          edition: '2',
          pages: 228,
          description:
            'Enquanto Abigail Cable retoma a sua vida ao lado do marido Matt, o Monstro do P\u00e2ntano se pergunta a respeito de estranhas profecias que parecem se aproximar e do significado delas. Aos poucos Abby vai descobrindo que algo estranho est\u00e1 acontecendo em sua vida aparentemente perfeita e que as coisas n\u00e3o s\u00e3o o que parecem.',
          publishing_date: new Date('2014-10-01'),
          format: '(17 x 26 cm)\nColorido/Lombada quadrada',
          price: '24.90',
          thumbnail: 'static/covers/789765352158602.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 19,
          isbn: '9788573519990',
          title: 'One Piece',
          edition: '14',
          pages: 196,
          description:
            'Culpando os chap\u00e9us de palha pela bomba, Dorey ataca Luffy. O garoto tem dificuldades contra o gigante, mas ap\u00f3s uma dura luta consegue derrubar Dorey, acalmando um pouco o gigante. Em outra parte da ilha, Mr. 5 se encontra com Mr. 3 em uma casa feita de cera no meio da floresta. O agente faz pouco dos dois de n\u00famero mais elevado e em seguida sugere um plano para a captura dos dois gigantes que ainda possuem recompensas ativas.',
          publishing_date: new Date('2013-03-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/978-8573519990.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 20,
          isbn: '9788542600018',
          title: 'One Piece',
          edition: '15',
          pages: 220,
          description:
            'Ap\u00f3s a batalha, para surpresa geral, Dorey levanta-se. Burogy se alegra ao ver que seu amigo ainda est\u00e1 vivo. Enquanto isso no esconderijo de Mr. 3, Sanji atende o Den Den Mushi e fala diretamente com Mr. 0, o l\u00edder da Baroque Works. O cozinheiro diz ao Shichibukai que havia matado os chap\u00e9us de palha, passando-se por Mr. 3. Em meio a isso, ele \u00e9 atacado e derrota os Unluckies, mas faz Crocodile acreditar em sua hist\u00f3ria.',
          publishing_date: new Date('2013-04-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/9788542600018.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 21,
          isbn: '9788542600322',
          title: 'One Piece',
          edition: '16',
          pages: 196,
          description:
            'Os Rapans provocam uma avalanche. Luffy e Sanji fazem o poss\u00edvel para fujir dela e acabam precisando descer a montanha, ainda perseguidos pelos monstruosos coelhos. Para o bem de Nami, Sanji lan\u00e7a Luffy para um lugar seguro, sendo assim atingido pela avalanche e se perdendo em meio \u00e0 neve. Enquanto isso, parece que a avalanche afetou as \u00e1reas abaixo tamb\u00e9m, e Wapol e sua tripula\u00e7\u00e3o fogem. Ap\u00f3s enfim se recuperarem do evento, o antigo rei decide voltar a seu castelo.',
          publishing_date: new Date('2013-05-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/978-8542600322.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 22,
          isbn: '9788583680758',
          title: 'Demolidor Por Frank Miller & Klaus Janson',
          edition: '1',
          pages: 340,
          description:
            'Matt \u00e9 v\u00edtima de sequestro por uma quadrilha que pretende lev\u00e1-lo ao Arauto da Morte, nem a Vi\u00fava Negra consegue impedir o bando. \nNo cemit\u00e9rio o Arauto da Morte quer se vingar do Homem Sem Medo e a luta se inicia.',
          publishing_date: new Date('2014-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '92.00',
          thumbnail: 'static/covers/9788583680758.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 23,
          isbn: '9788573515466',
          title: 'Coringa',
          edition: null,
          pages: 136,
          description:
            'Um lado mais sombrio e perturbador do homem mais perigoso de Gotham: o Coringa. Ap\u00f3s mais uma passagem pelo Asilo Arkham, Coringa descobre \u2019sua cidade\u2019 dividida entre g\u00e2ngsters e her\u00f3is uniformizados. N\u00e3o contente em ficar com apenas uma fatia do crime, Coringa decide tomar tudo para si do jeito que for necess\u00e1rio.',
          publishing_date: new Date('2011-10-01'),
          format: '(17 x 26 cm)\nColorido/Capa dura',
          price: '24.90',
          thumbnail: 'static/covers/978-8573515466.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 24,
          isbn: '9788565484060',
          title: 'Grandes Astros Superman',
          edition: null,
          pages: 308,
          description:
            'Superman vai at\u00e9 o sol para salvar a tripula\u00e7\u00e3o da nave "Ray Bradbury". No entanto, a amea\u00e7a se revela uma armadilha de Lex Luthor - que, ao descobrir que est\u00e1 envelhecendo, resolve matar seu velho inimigo com uma sobrecarga nas suas baterias solares de seu corpo',
          publishing_date: new Date('2012-10-01'),
          format: '(19 x 28 cm)\nColorido/Capa dura',
          price: '84.00',
          thumbnail: 'static/covers/9788565484060.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 25,
          isbn: '789765352158603',
          title: 'Saga do Monstro do P\u00e2ntano',
          edition: '3',
          pages: 212,
          description:
            'In\u00edcio da \u00e9pica saga "G\u00f3tico Americano", onde Alan Moore aumenta a dose de terror na revista e a liga \u00e0 saga "Crise Nas Infinitas Terras". Nesta primeira HQ, o Monstro do P\u00e2ntano e sua amada Abby Cable est\u00e3o aproveitando sua intimidade no Bayou at\u00e9 que sua paz \u00e9 perturbada por um sarc\u00e1stico visitante: um mago ingl\u00eas chamado John Constantine, que avisa ao Monstro que um grande mal recair\u00e1 sobre o mundo e que s\u00f3 ele poder\u00e1 impedir',
          publishing_date: new Date('2014-12-01'),
          format: '(17 x 26 cm)\nColorido/Lombada quadrada',
          price: '23.90',
          thumbnail: 'static/covers/789765352158603.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 26,
          isbn: '9788565484008',
          title: 'Preacher',
          edition: '1',
          pages: 200,
          description:
            'A jornada do reverendo Jesse Custer para acertar as contas com Deus come\u00e7a aqui. Ao ministrar um serm\u00e3o ap\u00f3s um epis\u00f3dio pol\u00eamico em sua comunidade (envolvendo Jesse, um bar e muito u\u00edsque), o pastor foi protagonista de um acontecimento religioso de primeira grandeza e teve contato imediato com G\u00eanesis, uma entidade meio anjo, meio dem\u00f4nio, cuja natureza jogou Jesse em uma cruzada moderna.',
          publishing_date: new Date('2012-06-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '58.00',
          thumbnail: 'static/covers/978-8565484008.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 27,
          isbn: '9788573513769',
          title: 'Batman - O Cavaleiro das Trevas',
          edition: null,
          pages: 516,
          description:
            'A morte violenta de seus pais levou Batman a combater o crime em todas as suas formas durante muitos anos. Por\u00e9m, ningu\u00e9m ouviu falar dele em Gotham City na \u00faltima d\u00e9cada. Isto \u00e9, at\u00e9 agora',
          publishing_date: new Date('2011-09-01'),
          format: '(19 x 28 cm)\nColorido/Capa dura',
          price: '90.00',
          thumbnail: 'static/covers/978-8573513769.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 28,
          isbn: '9788583680659',
          title: 'Batman - A Corte das Corujas',
          edition: null,
          pages: 180,
          description:
            'Enquanto reflete sobre a natureza de Gotham, Bruce Wayne apresenta seu plano de reforma urbana para a cidade. E um novo assassinato levanta suspeitas sobre um dos mais antigos aliados de Batman',
          publishing_date: new Date('2014-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '27.90',
          thumbnail: 'static/covers/978-8583680659.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 29,
          isbn: '789765352158604',
          title: 'Saga do Monstro do P\u00e2ntano',
          edition: '4',
          pages: 224,
          description:
            'Chester Williams, um naturalista e ocasional traficante de drogas, encontra um dos tub\u00e9rculos que crescem no corpo do Monstro do P\u00e2ntano. Ele decide ent\u00e3o dividir o fruto em tr\u00eas partes, destinadas a si mesmo, \u00e0 esposa condenada de um amigo e um de seus mais desregrados clientes. Os resultados s\u00e3o imprevis\u00edveis!',
          publishing_date: new Date('2015-04-01'),
          format: '(17 x 26 cm)\nColorido/Lombada quadrada',
          price: '24.90',
          thumbnail: 'static/covers/789765352158604.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 30,
          isbn: '9788542600513',
          title: 'One Piece',
          edition: '20',
          pages: 212,
          description:
            'Luffy manda seus companheiros seguirem sem ele, enquanto ele fica para enfrentar Crocodile. Apesar de cheia de d\u00favidas, Vivi decide seguir sem o capit\u00e3o, com a promessa de encontr\u00e1-lo em Alubarna. Ap\u00f3s uma breve conversa, Miss All Sunday tem seu nome revelado por Mr. 0 e parte na frente, deixando Luffy e Crocodile para lutar. O Shichibukai d\u00e1 a seu oponente um tempo antes de come\u00e7ar a lutar a s\u00e9rio, mas n\u00e3o importa o que Luffy fa\u00e7a e que ataque usa, nada afeta seu inimigo',
          publishing_date: new Date('2013-09-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/978-8542600513.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 31,
          isbn: '9788583680697',
          title: 'X-Men: Deus Ama, O Homem Mata',
          edition: null,
          pages: 104,
          description:
            'O Professor Charles Xavier e seus pupilos X-Men (Ciclope, Tempestade, Wolverine, Noturno, Kitty Pryde e Colossus) entram na mira do fan\u00e1tico pastor William Stryker, um influente religioso que considera os mutantes uma cria diab\u00f3lica e uma afronta contra Deus e Sua Cria\u00e7\u00e3o. \nSeja com suas palavras, seja com sua mil\u00edcia assassina de mutantes, os Purificadores, Stryker quer guerra e at\u00e9 Magneto se unir\u00e1 aos her\u00f3is nesse confronto feroz combatido n\u00e3o s\u00f3 com punhos, mas com palavras e sentimentos.',
          publishing_date: new Date('2014-11-01'),
          format: '(20,5 x 27,5 cm)\nColorido/Capa dura',
          price: '22.90',
          thumbnail: 'static/covers/978-8583680697.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 32,
          isbn: '789765352629101',
          title: '20th Century Boys',
          edition: '1',
          pages: 218,
          description:
            "A Humanidade n\u00e3o teria superado o desastre do final do s\u00e9culo 20 se n\u00e3o fosse por 'eles'. Em 1969, quando ainda eram crian\u00e7as, 'eles' criaram um simbolo. Em 1991, quando a crise se aproximava lentamente, o s\u00edmbolo ressurgiu.",
          publishing_date: new Date('2012-09-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/789765352629101.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 33,
          isbn: '9788583681106',
          title: 'Revelado',
          edition: '1',
          pages: 356,
          description:
            'O Rei do Crime cai numa emboscada organizada por Silke, e \u00e9 aparentemente assassinado. Uma semana antes, Matt Murdock est\u00e1 num julgamento contra uma grande multinacional. Ap\u00f3s ganhar a disputa judicial, na sa\u00edda do tribunal, ele sofre um misterioso atentado, e o Demolidor \u00e9 obrigado a ir atr\u00e1s do respons\u00e1vel. Existir\u00e1 uma rela\u00e7\u00e3o entre a tentativa de homic\u00eddio a Matt e a morte do Rei?',
          publishing_date: new Date('2015-06-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '92.00',
          thumbnail: 'static/covers/978-8583681106.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 34,
          isbn: '9788583680901',
          title: 'Aquaman',
          edition: null,
          pages: 148,
          description:
            'O soberano dos mares tomou sua decis\u00e3o. De agora em diante, seu lar ser\u00e1 a superf\u00edcie e, sua miss\u00e3o, proteger os habitantes desse mundo. Mas as profundezas guardam surpresas bastante desagrad\u00e1veis para o her\u00f3i. Vindos das fossas abissais, criaturas pavorosas planejam um ataque cruel \u00e0 pequena cidade pr\u00f3xima ao farol habitado por Aquaman.',
          publishing_date: new Date('2015-05-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '25.90',
          thumbnail: 'static/covers/978-8583680901.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 35,
          isbn: '9788565484701',
          title: 'Batman',
          edition: '1',
          pages: 152,
          description:
            'Em uma Gotham City onde amigo e inimigos s\u00e3o indistingu\u00edveis, o caminho de Bruce Wayne para se tornar o Cavaleiro das Trevas est\u00e1 mais cheio de obst\u00e1culos do que nunca.\nObcecado em punir os verdadeiros assassinos de seus pais, e o policial corrupto que o deixou em liberdade, a sede de vingan\u00e7a de Wayne alimenta sua cruzada e ningu\u00e9m, nem mesmo Alfred, pode det\u00ea-lo.',
          publishing_date: new Date('2013-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '21.90',
          thumbnail: 'static/covers/978-8565484701.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 36,
          isbn: '19',
          title: 'Demolidor',
          edition: '1',
          pages: 124,
          description:
            'Num futuro pr\u00f3ximo, o Rei do Crime e o Demolidor s\u00e3o assassinados. O rep\u00f3rter Ben Urichc tem uma \u00faltima hist\u00f3ria a escrever: qual o \u00faltimo segredo de Matt Murdock? Para responder dever\u00e1 esmiu\u00e7ar o passado de Murdok, seus antigos amores, seus pecados e enigmas que circundam sua morte. Ben est\u00e1 sendo seguido enquanto realiza investiga\u00e7\u00f5es, mas por quem?',
          publishing_date: new Date('2015-02-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Lombada quadrada',
          price: '18.90',
          thumbnail: 'static/covers/B019QHXBUS.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 37,
          isbn: '9788565484671',
          title: 'Justiceiro Max',
          edition: null,
          pages: 124,
          description:
            'Os chefes das maiores fam\u00edlias criminosas se uniram para acabar com o Justiceiro para sempre. Eles montaram uma armadilha para Frank usando um subordinado qualquer chamado Wilson Fisk para interpretar \u201cO Rei do Crime\u201d, uma figura imagin\u00e1ria que, sabem eles, chamar\u00e1 a aten\u00e7\u00e3o de Frank Castle. Com a emboscada armada, cabe aos seus arquitetos simplesmente aguardar o Justiceiro morder a isca.',
          publishing_date: new Date('2014-02-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '22.90',
          thumbnail: 'static/covers/978-8565484671.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 38,
          isbn: '9788583680321',
          title: 'Batman',
          edition: null,
          pages: 116,
          description:
            'A hist\u00f3ria \u00e9 inspirada em Um Conto de Natal, de Charles Dickens, mas adaptado para Gotham City. Ao inv\u00e9s do velho Scrooge e de seus fantasmas, aqui \u00e9 o Batman quem tem que encontrar os termos ideais para ficar em paz com seu passado, presente e futuro para enfrentar a sua galeria de vil\u00f5es e as amea\u00e7as sombrias de hoje em dia, enquanto explora o que significa ser o her\u00f3i que \u00e9',
          publishing_date: new Date('2015-02-01'),
          format: '(19 x 28 cm)\nColorido/Capa dura',
          price: '22.90',
          thumbnail: 'static/covers/978-8583680321.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 39,
          isbn: '9788573516630',
          title: 'Kick-Ass',
          edition: '1',
          pages: 212,
          description:
            'O que acontece quando um cara comum numa roupa de l\u00e1tex fica frente a frente com o submundo do crime? \u00c9 isso que o jovem Dave Lizewski est\u00e1 prestes a descobrir. Afinal, as pessoas t\u00eam apenas uma vida, e Dave quer que a dele seja empolgante. A qualquer pre\u00e7o.',
          publishing_date: new Date('2010-06-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '60.00',
          thumbnail: 'static/covers/978-8573516630.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 40,
          isbn: '9788565484770',
          title: 'Surfista Prateado',
          edition: null,
          pages: 92,
          description:
            'O \u00fanico oponente do Devorador de Mundos \u00e9 o her\u00f3i que ele aprisionou na Terra: o Surfista Prateado, Galactus jurou n\u00e3o consumir o planeta, mas e se, em vez disso, ele transformar a civiliza\u00e7\u00e3o em seus adoradores? Aos terr\u00e1queos o semideus promete um futuro melhor, mas nenhuma outra pessoa conhece os verdadeiros prop\u00f3sitos dele do que o Surfista Prateado, seu antigo arauto. Aos poss\u00edveis disc\u00edpulos do Devorador, resta somente assistir ao colossal confronto das duas divindades intergal\u00e1cticas!',
          publishing_date: new Date('2014-03-01'),
          format: '(19 x 28 cm)\nColorido/Capa dura',
          price: '21.90',
          thumbnail: 'static/covers/978-8565484770.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 41,
          isbn: '9788565484572',
          title: 'Turma da M\u00f4nica: La\u00e7os',
          edition: '2',
          pages: 80,
          description:
            'O Floquinho desapareceu. Para encontrar seu cachorro de estima\u00e7\u00e3o, Cebolinha conta com os amigos Casc\u00e3o, M\u00f4nica e Magali e, claro, um plano \u201cinfal\u00edvel\u201d.',
          publishing_date: new Date('2013-06-01'),
          format: '(19 x 26 cm)\nColorido/Capa dura',
          price: '29.90',
          thumbnail: 'static/covers/978-8565484572.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 42,
          isbn: '9788583681052',
          title: 'Gotham. DPGC. No Cumprimento do Dever',
          edition: '1',
          pages: 244,
          description:
            'N\u00e3o \u00e9 f\u00e1cil ser um policial em Gotham City\u2026 N\u00e3o \u00e9 preciso apenas lidar com a viol\u00eancia e a corrup\u00e7\u00e3o de uma cidade infestada pelo crime (e com os criminosos mais insanos e homicidas da hist\u00f3ria), mas tamb\u00e9m levar em conta um vigilante decidido a jogar pelas pr\u00f3prias regras. Os bons policiais da cidade trabalham dia e noite limpando a bagun\u00e7a que \u00e9 deixada para tr\u00e1s pela guerra de um homem s\u00f3 contra o crime. Por\u00e9m, quando um dos membros do departamento de pol\u00edcia \u00e9 morto pelo Senhor Frio, os Melhores de Gotham entram em uma luta contra o tempo para prender o criminoso sem a ajuda do Cavaleiro das Trevas. Pouco depois, a detetive Renee Montoya \u00e9 \u201cdesmascarada\u201d como homossexual e descobre seu ambiente de trabalho e sua vida pessoal virados de cabe\u00e7a para baixo. E as coisas ficam ainda mais complicadas quando ela \u00e9 raptada pelo Duas-Caras. S\u00e9rie ganhadora de diversos pr\u00eamios da cr\u00edtica especializada, Gotham \u00e9 trazida at\u00e9 voc\u00ea pelos aclamados escritores Ed Brubaker e Greg Rucka, acompanhados pelo artista Michael Lark.',
          publishing_date: new Date('2015-09-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '66.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 43,
          isbn: '9788583681632',
          title: 'Gotham - Alvos F\u00e1ceis',
          edition: '2',
          pages: 292,
          description:
            'Como se n\u00e3o bastasse lidar com a viol\u00eancia e a corrup\u00e7\u00e3o de uma cidade infestada pelo crime (e com os criminosos mais insanos e cru\u00e9is da hist\u00f3ria), a pol\u00edcia de Gotham tamb\u00e9m deve levar em conta um vigilante decidido a jogar pelas pr\u00f3prias regras. E, para piorar a situa\u00e7\u00e3o, o Coringa est\u00e1 aterrorizando a cidade na \u00e9poca de Natal, executando pessoas aleatoriamente com um rifle. E ningu\u00e9m, do prefeito ao cidad\u00e3o mais comum, est\u00e1 a salvo! A ca\u00e7ada come\u00e7a, mas uma atitude desconcertante do Palha\u00e7o do Crime deixa todos perplexos. O que o arqui-inimigo do Homem-Morcego realmente pretende? E ainda nesse volume: a hist\u00f3ria da garota que tem como trabalho ligar o Batsinal. Uma s\u00e9rie de assassinatos que acaba chamando a aten\u00e7\u00e3o da Ca\u00e7adora. E um velho caso que amea\u00e7a piorar (ainda mais) a vida do detetive Harvey Bullock.',
          publishing_date: new Date('2016-08-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '52.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 44,
          isbn: '9788583681953',
          title: 'Gotham DPGC - Sob Suspeita - Volume 1',
          edition: '3',
          pages: 228,
          description:
            'Uma violenta guerra de gangues estoura em Gotham City. Ap\u00f3s um tr\u00e1gico erro, a pol\u00edcia sente que n\u00e3o pode mais confiar no Batman, e o comiss\u00e1rio toma uma decis\u00e3o rigorosa: o Cavaleiro das Trevas agora \u00e9 um homem procurado, e o famoso Batsinal \u00e9 removido do telhado do DPGC. E isso n\u00e3o poderia ter acontecido em pior hora, j\u00e1 que a Unidade de Crimes Hediondos vai precisar encarar um supervil\u00e3o com quem nunca lidou, e com a vida de um bom policial na berlinda\u2026 Enquanto o conflito entre as gangues cobra seu pre\u00e7o da cidade, os parceiros Renee Montoya e Crispus Allen d\u00e3o in\u00edcio a eventos que mudar\u00e3o suas vidas para sempre. Para manter Gotham a salvo sem a ajuda do Homem-Morcego, a dupla ter\u00e1 que fazer inimigos bem poderosos\u2026 e encarar algumas verdades dolorosas sobre seus segredos mais sombrios.',
          publishing_date: new Date('2017-02-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '46.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 45,
          isbn: '9788583682264',
          title: 'Providence',
          edition: null,
          pages: 176,
          description:
            'Nova York, 1919. Robert Black \u00e9 um rep\u00f3rter que h\u00e1 pouco tempo encontrou seu pr\u00f3prio lugar no mundo. O s\u00fabito suic\u00eddio de uma pessoa querida o conduz por uma estrada misteriosa, na descoberta do lado sombrio dos Estados Unidos. \u00c9 uma estrada sinuosa, labir\u00edntica. \u00c9 a estrada para Providence. Pela primeira vez no Brasil, o primeiro tomo da obra-prima de Alan Moore e Jacen Burrows.',
          publishing_date: new Date('2017-05-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '62.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 46,
          isbn: '9788545702870',
          title: 'AKIRA',
          edition: '1',
          pages: 364,
          description:
            'Um dos maiores mang\u00e1s de todos os tempos volta ao Brasil em uma edi\u00e7\u00e3o especial totalmente remasterizada e em seu formato e leitura originais. Neste primeiro volume, em um mundo p\u00f3s-apocaliptico, conhecemos Kaneda e Tetsuo, dois amigos membros de uma gangue de motoqueiros arruaceiros que ter\u00e3o suas vidas drasticamente mudadas ap\u00f3s o atropelamento de uma estranha crian\u00e7a. Depois do acidente Tetsuo passa a despertar estranhos poderes que acabam chamando a aten\u00e7\u00e3o do Governo o qual, atualmente, trabalha em experi\u00eancias secretas com paranormais.',
          publishing_date: new Date('2017-06-01'),
          format: '(18 x 26 cm)\nColorido/Preto e branco/Lombada quadrada',
          price: '60.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 47,
          isbn: '9788545702320',
          title: 'The Ghost in the Shell',
          edition: null,
          pages: 352,
          description:
            'Ghost in the Shell foi o futuro dist\u00f3pico de 2029, onde a alta tecnologia se mistura a uma sociedade decadente e desigual.\u00c9 nesse mundo \u00e0 beira do colapso que a Major Motoko Kusanagi encabe\u00e7a a Se\u00e7\u00e3o 9 da Seguran\u00e7a P\u00fablica japonesa. Motoko \u00e9 uma ciborgue altamente treinada incumbida de desmantelar uma s\u00e9rie de crimes cibern\u00e9ticos realizados por um hacker conhecido como o Mestre dos Fantoches. Em meio \u00e0 ca\u00e7a ao criminoso virtual, Masamune Shirow insere na trama questionamentos existencialistas, ponderando at\u00e9 mesmo se algu\u00e9m provido meramente de Intelig\u00eancia Artificial \u00e9, de fato, um ser vivo. E foi exatamente essa mistura de fic\u00e7\u00e3o cient\u00edfica, a\u00e7\u00e3o e temas filos\u00f3ficos que fizeram do mang\u00e1 The Ghost in the Shell uma leitura obrigat\u00f3ria.',
          publishing_date: new Date('2016-12-01'),
          format: '(16,5 x 24 cm)\nColorido/Preto e branco/Lombada quadrada',
          price: '64.90',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 48,
          isbn: '9788550402796',
          title: 'Valerian Integral',
          edition: '1',
          pages: 160,
          description:
            'Fruto da imagina\u00e7\u00e3o transbordante de Pierre Christin e Jean-Claude M\u00e9zi\u00e8res, os personagens de Valerian e Laureline surgiram pela primeira vez nas p\u00e1ginas de PILOTE, em 1967. Por sua inventividade e aud\u00e1cia, a s\u00e9rie rapidamente se tornou refer\u00eancia absoluta para os leitores de hist\u00f3rias em quadrinhos de fic\u00e7\u00e3o cient\u00edfica.',
          publishing_date: new Date('2017-05-01'),
          format: '(21,5 x 29 cm)\nColorido/Lombada quadrada',
          price: '35.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 49,
          isbn: '9788550404134',
          title: 'Valerian Integral',
          edition: '2',
          pages: 172,
          description:
            'Fruto da imagina\u00e7\u00e3o transbordante de Pierre Christin e Jean-Claude M\u00e9zi\u00e8res, os personagens de Valerian e Laureline surgiram pela primeira vez nas p\u00e1ginas de PILOTE, em 1967. Por sua inventividade e aud\u00e1cia, a s\u00e9rie rapidamente se tornou refer\u00eancia absoluta para os leitores de hist\u00f3rias em quadrinhos de fic\u00e7\u00e3o cient\u00edfica.',
          publishing_date: new Date('2017-08-01'),
          format: '(21,5 x 29 cm)\nColorido/Lombada quadrada',
          price: '58.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 50,
          isbn: '9788583681915',
          title: 'Skreemer',
          edition: null,
          pages: 180,
          description:
            'O coronel Nick Fury, diretor da SHIELD, descobre que uma mente sinistra est\u00e1 financiando alguns dos supervil\u00f5es mais perigosos do planeta. Decidido a combater a terr\u00edvel e sombria amea\u00e7a, monta uma equipe de opera\u00e7\u00f5es secretas composta por Homem-Aranha, Wolverine, Demolidor, Capit\u00e3o Am\u00e9rica e Luke Cage. Por\u00e9m, um ano depois, o passado volta para assombrar os integrantes e uma s\u00e9rie de eventos come\u00e7a a ocorrer, colocando em risco n\u00e3o apenas suas vidas, mas de todas as pessoas que lhes s\u00e3o caras.',
          publishing_date: new Date('2017-07-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '59.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 51,
          isbn: '9788575321669',
          title: 'Preacher - A Caminho do Texas',
          edition: '1',
          pages: 200,
          description: `A jornada do reverendo Jesse Custer para acertar as contas com Deus
            come\u00e7a aqui. Ao ministrar um serm\u00e3o ap\u00f3s um
            epis\u00f3dio pol\u00eamico em sua comunidade (envolvendo Jesse,
              um bar e muito u\u00edsque), o pastor foi protagonista de um acontecimento
              religioso de primeira grandeza e teve contato imediato com G\u00eanesis,
              uma entidade meio anjo, meio dem\u00f4nio, cuja natureza jogou Jesse em uma
              cruzada moderna. Amalgamado com a criatura, Jesse Custer ganhou uma linha
              direta com os mist\u00e9rios da Cria\u00e7\u00e3o e seus principais
              personagens. E, dentre todos estes, nenhum \u00e9 mais importante do que Deus.
              A miss\u00e3o do reverendo agora \u00e9 a mais grandiosa (e perigosa) de todas:
              partir em busca do pr\u00f3prio Criador atr\u00e1s de respostas!
              E ele n\u00e3o estar\u00e1 sozinho em seu caminho. Tulipa, uma ex-namorada,
              e Cassidy, um irland\u00eas envolto em mist\u00e9rios, entram em cena
              trazidos por uma coincid\u00eancia (ou pela Divina Provid\u00eancia)
              para participarem da jornada. O primeiro passo est\u00e1 dado!
              A Caminho do Texas traz o in\u00edcio da saga de Preacher.`,
          publishing_date: new Date('2012-06-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '58.00',
          thumbnail: 'static/covers/978-8565484008.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 52,
          isbn: '9788565484299',
          title: 'Preacher - At\u00e9 o Fim do Mundo',
          edition: '2',
          pages: 256,
          description:
            'Tendo a alma mesclada com a entidade angelical-demon\u00edaca conhecida como G\u00eanesis, o reverendo Jesse Custer \u00e9 agora o \u00fanico pastor na Terra que realmente tem o dom da Palavra de Deus. Qualquer um que ou\u00e7a seus comandos precisa obedecer incondicionalmente a eles \u2013 ou quase todo mundo. Quando seu inimigo mais letal chega para lev\u00e1-lo at\u00e9 a fazenda da fam\u00edlia, Jesse descobre que n\u00e3o pode confiar tanto n\u2019A Palavra quanto acreditava. E isso \u00e9 uma p\u00e9ssima not\u00edcia para o pregador e sua namorada, Tulipa O\u2019Hare, porque chegou o momento de encarar a figura que transformou a inf\u00e2ncia de Jesse em um inferno: sua av\u00f3. Mas por pior que a senhora Marie L\u2019Angelle possa ser, ainda existem pessoas mais perigosas no mundo e elas j\u00e1 ouviram falar do poder d\u2019A Palavra. Jesse ainda n\u00e3o sabe, mas j\u00e1 foi envolvido na maior e mais terr\u00edvel conspira\u00e7\u00e3o da hist\u00f3ria do mundo \u2013 e vai descobrir como pode ser dif\u00edcil dizer \u201cn\u00e3o\u201d.',
          publishing_date: new Date('2012-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '67.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 53,
          isbn: '9788565484565',
          title: 'Preacher - Orgulho Americano',
          edition: '3',
          pages: 236,
          description:
            'O reverendo Jesse Custer quase perdeu a f\u00e9 quando teve a alma mesclada com a entidade angelical-demon\u00edaca conhecida como G\u00eanesis. O resultado desse encontro explosivo o fez virar o \u00fanico pastor na Terra que realmente tem o dom da Palavra de Deus e lhe deu um novo objetivo que o levou para uma das jornadas mais bizarras de que se tem not\u00edcia: ele est\u00e1 em busca de Deus! Mas os caminhos at\u00e9 Ele s\u00e3o tortuosos e agora Jesse e Tulipa, a namorada que ele reencontrou depois de muito tempo, precisam passar pela Fran\u00e7a para resgatar seu fiel amigo, o vampiro Cassidy. L\u00e1, ele \u00e9 mantido prisioneiro pelo Graal, uma organiza\u00e7\u00e3o perigosa e secreta cujo prop\u00f3sito \u00e9 o de proteger o novo Messias. Mas Herr Starr, um obstinado l\u00edder dentro da organiza\u00e7\u00e3o que tem seus pr\u00f3prios planos, pretende que esse Messias seja Jesse Custer. E \u00e9 a\u00ed que a hist\u00f3ria complica.',
          publishing_date: new Date('2013-06-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '65.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 54,
          isbn: '9788565484749',
          title: 'Preacher - Hist\u00f3rias Antigas',
          edition: '4',
          pages: 228,
          description:
            "O reverendo Jesse Custer quase perdeu a f\u00e9 quando teve a alma mesclada com a entidade angelical-demon\u00edaca conhecida como G\u00eanesis. O resultado desse encontro lhe deu um novo objetivo e o levou a uma das jornadas mais improv\u00e1veis de que se tem not\u00edcia: Jesse est\u00e1 em busca de Deus para for\u00e7\u00e1-Lo a responder por suas falhas e omiss\u00f5es, e responsabiliz\u00e1-Lo por abandonar a humanidade. Mas tal miss\u00e3o chega a um hiato que aproveitaremos para conhecer mais sobre as hist\u00f3rias de alguns bizarros personagens que cruzaram o caminho do reverendo durante essa singular cruzada. O Santo dos Assassinos \u2013 a n\u00eamese sobrenatural de Jesse Custer \u2013 tem sua origem contada, indo das g\u00e9lidas plan\u00edcies do Velho Oeste americano at\u00e9 as profundezas mais quentes do Inferno. Jody e T.C. \u2013 os dois capangas da sra. Marie L'Angelle, a cruel av\u00f3 de Jesse \u2013 vivem uma aventura do passado repleta de a\u00e7\u00e3o e pancadaria. J\u00e1 Cara-de-Cu \u2013 um dos personagens mais antol\u00f3gicos dos quadrinhos \u2013 tem os bastidores de sua cria\u00e7\u00e3o e da forma\u00e7\u00e3o de sua personalidade desvendados. Hist\u00f3rias Antigas \u00e9 o quarto cap\u00edtulo da saga de PREACHER, uma das hist\u00f3rias em quadrinhos mais aclamadas dos anos 90",
          publishing_date: new Date('2014-10-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '64.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 55,
          isbn: '9788573515497',
          title: 'Watchmen',
          edition: null,
          pages: 464,
          description:
            'Uma das Graphic Novels mais influentes de todos os tempos e um eterno bestseller, Watchmen s\u00f3 cresceu em estatura desde sua publica\u00e7\u00e3o original, como miniss\u00e9rie, em 1986. Esta edi\u00e7\u00e3o de luxo, com capa dura, papel especial e formato diferenciado, traz a lend\u00e1ria saga escrita por Alan Moore e desenhada por Dave Gibbons, totalmente recolorida digitalmente por John Higgings, o colorista original. N\u00e3o apenas isso, o volume de 460 p\u00e1ginas tamb\u00e9m apresenta uma quantidade de extras jamais vista no Brasil, trazendo trechos do roteiro original, esbo\u00e7os de Gibbons, coment\u00e1rios sobre os personagens, textos dos criadores e mais. Uma edi\u00e7\u00e3o primorosa que n\u00e3o pode faltar na estante de nenhum colecionador. Uma edi\u00e7\u00e3o primorosa que n\u00e3o pode faltar na estante de nenhum colecionador. O ano \u00e9 1985. Os Estados Unidos s\u00e3o uma na\u00e7\u00e3o totalit\u00e1ria e fechada, isolada do resto do mundo. A presen\u00e7a de arsenais nucleares e dos chamados super-her\u00f3is mant\u00e9m um certo equil\u00edbrio entre as for\u00e7as do planeta... at\u00e9 que o rel\u00f3gio do fim do mundo come\u00e7a a marchar para a meia-noite e a ra\u00e7a humana para um abismo sem-fim. A sombria e inigual\u00e1vel trama tem in\u00edcio com ilus\u00f5es paran\u00f3icas do supostamente insano her\u00f3i Rorschach, um dos Watchmen que patrulhavam os EUA d\u00e9cadas atr\u00e1s. Mas ele estaria realmente insano ou na verdade teria descoberto uma s\u00f3rdida conspira\u00e7\u00e3o para assassinar super-her\u00f3is -- ou, pior ainda, milh\u00f5es de civis inocentes? Fugindo da lei, Rorschach junta-se a ex-companheiros do passado em uma desesperada tentativa de salvar suas pr\u00f3prias vidas... e o que acabam descobrindo, al\u00e9m de abalar suas estruturas, poder\u00e1 alterar o pr\u00f3prio destino do planeta Terra! Seguindo duas gera\u00e7\u00f5es de her\u00f3is mascarados, desde a Segunda Guerra at\u00e9 os tensos anos da Guerra Fria, surge esta pioneira epop\u00e9ia de \u00f3dio, amor, reencontros imposs\u00edveis, grandes reviravoltas e muita a\u00e7\u00e3o, como s\u00f3 a criatividade de Alan Moore e Dave Gibbons poderia conceber!',
          publishing_date: new Date('2011-11-01'),
          format: '(19 x 27,5 cm)\nColorido/Capa dura',
          price: '110.00',
          thumbnail: 'static/covers/9788573515497.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 56,
          isbn: '9788565484640',
          title: 'Reino do Amanh\u00e3',
          edition: null,
          pages: 340,
          description:
            'Em um futuro n\u00e3o muito distante, a Terra se tornou o reino dos super-her\u00f3is. Infelizmente para os habitantes n\u00e3o t\u00e3o poderosos do planeta, estes \u201cher\u00f3is\u201d v\u00eam se tornando cada vez mais irrespons\u00e1veis e destrutivos, colocando em risco a sobreviv\u00eancia do mundo inteiro. E para piorar a situa\u00e7\u00e3o, o \u00fanico ser que pode devolver o bom-senso a essa ra\u00e7a de novas e irasc\u00edveis divindades, o envelhecido Superman, se aposentou e se recolheu h\u00e1 anos. Sobre essa premissa b\u00e1sica, o roteirista Mark Waid e o premiado ilustrador Alex Ross constru\u00edram Reino do Amanh\u00e3, uma das HQs mais marcantes e relevantes da d\u00e9cada de 1990, que explora o moderno mito do super-her\u00f3i de forma nunca antes vista. Agora, essa obra prima da nona arte volta ao Brasil em uma edi\u00e7\u00e3o repleta de extras in\u00e9ditos no pa\u00eds e com acabamento de luxo!',
          publishing_date: new Date('2013-10-01'),
          format: '(19,5 X 30,5 cm)\nColorido/Capa dura',
          price: '89.00',
          thumbnail: 'static/covers/978-8565484640.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 57,
          isbn: '9788583680796',
          title: 'Preacher - Rumo ao Sul',
          edition: '5',
          pages: 232,
          description:
            'Ap\u00f3s destruir o quartel-general do todo-poderoso Graal e libertar Cassidy \u2013 seu companheiro de bebedeiras \u2013 do cativeiro, o reverendo Jesse Custer est\u00e1 prestes a se reunir com Tulipa O\u2019Hare \u2013 sua namorada de excelente mira \u2013 e retomar a ca\u00e7ada ao fugitivo Deus. Falta s\u00f3, \u00e9 claro, Tulipa o perdoar por ter sido deixada pra tr\u00e1s na miss\u00e3o de resgate\u2026Mas, para conseguir as respostas que busca, Jesse ter\u00e1 que mergulhar fundo na mente oculta de G\u00eanesis; a criatura anjo/dem\u00f4nio que se fundiu \u00e0 sua alma, e esse tipo de mergulho exige uma ajuda espiritual forte, uma que apenas a magia negra de raiz \u00e9 capaz de oferecer. Pra sorte de Jesse, Cassidy conhece um feiticeiro vodu em New Orleans que pode ajudar a destravar as mem\u00f3rias de G\u00eanesis. Mas, para o azar do pastor, Cassidy tamb\u00e9m tem um bando de aspirantes a vampiro atr\u00e1s de sua cabe\u00e7a na cidade\u2026 e eles est\u00e3o pouco se lixando para quem pode sair machucado enquanto ca\u00e7am seu alvo. Rumo ao Sul \u00e9 o quinto cap\u00edtulo da saga de Preacher.',
          publishing_date: new Date('2014-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '64.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 58,
          isbn: '9788583680741',
          title: 'Preacher - Guerra ao Sol',
          edition: '6',
          pages: 232,
          description:
            'O Todo Poderoso abandonou o Para\u00edso e o reverendo Jesse Custer \u2013 com a ajuda de Tulipa, sua namorada, e do vampiro irland\u00eas Cassidy, seu melhor amigo \u2013 pretende descobrir o porqu\u00ea. Mas o Senhor \u00e9 dif\u00edcil de ser localizado, mesmo para algu\u00e9m cuja alma est\u00e1 mesclada a uma entidade superpoderosa quase onipotente chamada G\u00eanesis. Para descobrir pistas do paradeiro Dele, Jesse precisa entrar fundo em sua pr\u00f3pria mente para conversar com seu convidado \u2013 e um punhado de peiote colhido sob o c\u00e9u do Arizon a pode ser justamente o ingrediente que faltava para esse bate-papo. Mas o que aguarda Jesse no Monument Valley, regi\u00e3o deserta dos Estados Unidos, \u00e9 algo muito menos espiritual: um regimento inteiro de tanques do Ex\u00e9rcito, comandado pelo rec\u00e9m-empossado novo comandante supremo do Graal: Herr Starr. Determinado a tomar o poder de G\u00eanesis para si, Starr est\u00e1 disposto a usar tudo no arsenal do Ex\u00e9rcito para for\u00e7ar Jesse a se submeter a sua vontade. Essa disputa n\u00e3o vai acontecer sem baixas',
          publishing_date: new Date('2014-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '65.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 59,
          isbn: '9788573519273',
          title: 'One Piece',
          edition: '7',
          pages: 196,
          description:
            'O restaurante flutuante Baratie est\u00e1 sob ataque do almirante pirata Don Krieg! Mas Luffy, Sanji e os cozinheiros do mar defender\u00e3o o legado de Zeff!!',
          publishing_date: new Date('2012-08-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '10.90',
          thumbnail: 'static/covers/9788573519273.jpg',
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 60,
          isbn: '9788573516357',
          title: 'Preacher - Salva\u00e7\u00e3o',
          edition: '7',
          pages: 260,
          description:
            'A busca por Deus levou Jesse Custer a uma peregrina\u00e7\u00e3o ao redor do mundo \u2013 e lhe custou muito caro. Ap\u00f3s uma batalha apocal\u00edptica com as for\u00e7as do Graal, Jesse caiu de um avi\u00e3o para uma morte praticamente certa\u2026 mas acordou um m\u00eas depois sem um olho e sem a mem\u00f3ria de como sobreviveu. Mas isso n\u00e3o foi nada perto da dor de ter encontrado a mulher que ama nos bra\u00e7os de seu melhor amigo! \n\nDepois de encarar isso, Jesse precisa de um tempo para pensar sobre seu objetivo e encontrar sua SALVA\u00c7\u00c3O \u2013 e, para essa busca, nada mais apropriado que a pequena cidade de Salvation, no Texas. Mas a cidade tem seus problemas, encarnados principalmente na forma de um psic\u00f3tico bar\u00e3o de matadouros chamado Odin Quincannon. Pra sorte de Jesse a cidade tem uma vaga no escrit\u00f3rio do Xerife \u2013 mas ser\u00e1 que ele est\u00e1 pronto para os segredos que se escondem nas entranhas de Salvation?',
          publishing_date: new Date('2010-02-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '62.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 61,
          isbn: '9788573516999',
          title: 'Preacher - \u00c0s Portas do Inferno',
          edition: '8',
          pages: 260,
          description:
            'Ap\u00f3s ter colaborado para limpar a cidade de Salvation, ter reencontrado sua m\u00e3e h\u00e1 muito perdida e sair mentalmente no bra\u00e7o com a entidade onipotente que vive dentro de sua cabe\u00e7a, o reverendo Jesse Custer finalmente est\u00e1 \u00c0s Portas Do Inferno e pronto para encarar o dano que sua suposta morte e aus\u00eancia infligiram em sua amada, Tulipa O\u2019Hare.\n\nMas essa \u00e9 a parte mais f\u00e1cil. A parte realmente complicada vai ser descobrir a verdadeira natureza do homem que ele considera seu melhor amigo: o vampiro irland\u00eas Cassidy. Quanto mais Jesse descobre sobre seu antigo companheiro de viagem, mais ele entra em contato com o lado negro e sombrio do vampiro e isso pode colocar a amizade dos dois em xeque.',
          publishing_date: new Date('2010-11-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '62.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 62,
          isbn: '9788573517699',
          title: 'Preacher - \u00c1lamo',
          edition: '9',
          pages: 232,
          description:
            'O reverendo Jesse Custer voltar\u00e1 a esse emblem\u00e1tico lugar de sacrif\u00edcio para encerrar a jornada que come\u00e7ou nos restos fumegantes de sua igreja muitos anos atr\u00e1s \u2013 uma cruzada para encontrar Deus e faz\u00ea-Lo responder por Suas a\u00e7\u00f5es. Depois de tudo pelo que Jesse e Tulipa O\u2019Hare, seu amor, passaram \u2013 trai\u00e7\u00e3o, morte, ressurrei\u00e7\u00e3o \u2013, finalmente chegou a hora de se fazer justi\u00e7a.\n\nMas eles ter\u00e3o a oportunidade de agir antes que Starr, l\u00edder obcecado do Grail, finalmente acerte as suas contas com o reverendo? Ou o \u00c1lamo ser\u00e1 o palco de outra derrota?',
          publishing_date: new Date('2011-09-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '60.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 63,
          isbn: '9788583680499',
          title: 'Y - O \u00daltimo Homem',
          edition: '1',
          pages: 320,
          description:
            'Em 2002 a Terra mudou para sempre. Todas as criaturas com um cromossomo Y morreram instantaneamente ao redor do globo. Com a perda de mais da metade da popula\u00e7\u00e3o, a sociedade est\u00e1 \u00e0 beira do colapso e cabe \u00e0s mulheres o fardo de juntar os peda\u00e7os e tentar manter nossa civiliza\u00e7\u00e3o. Mas esse \u201cgeneroc\u00eddio\u201d n\u00e3o foi t\u00e3o completo assim. Por alguma misteriosa raz\u00e3o, Yorick e seu macaco de estima\u00e7\u00e3o foram poupados do exterm\u00ednio. Do dia para a noite, esse desconhecido de vinte e poucos anos virou a pessoa mais importante do planeta e a chave para decifrar o mist\u00e9rio que varreu o sexo masculino do mapa. S\u00f3 que para ele a pessoa mais importante do planeta \u00e9 sua namorada, e ela est\u00e1 no outro hemisf\u00e9rio, na Austr\u00e1lia. E nada o impedir\u00e1 de ir ao encontro dela. Nessa cruzada por um mundo p\u00f3s-masculino, homem e macaco descobrir\u00e3o qu\u00e3o valiosos se tornaram: um como pr\u00eamio, o outro como alvo. Y \u2013 O \u00daLTIMO HOMEM',
          publishing_date: new Date('2015-09-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '98.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 64,
          isbn: '9788583681489',
          title: 'Y: O \u00daltimo Homem',
          edition: '2',
          pages: 238,
          description:
            'Em 2002 a Terra mudou para sempre. Todas as criaturas com um cromossomo Y morreram instantaneamente ao redor do globo. Com a perda de mais da metade da popula\u00e7\u00e3o, a sociedade est\u00e1 \u00e0 beira do colapso e cabe \u00e0s mulheres o fardo de juntar os peda\u00e7os e tentar manter nossa civiliza\u00e7\u00e3o. Mas esse \u201cgeneroc\u00eddio\u201d n\u00e3o foi t\u00e3o completo assim. Por alguma misteriosa raz\u00e3o, Yorick e seu macaco de estima\u00e7\u00e3o foram poupados do exterm\u00ednio. Do dia para a noite, esse desconhecido de vinte e poucos anos virou a pessoa mais importante do planeta e a chave para decifrar o mist\u00e9rio que varreu o sexo masculino do mapa. S\u00f3 que para ele a pessoa mais importante do planeta \u00e9 sua namorada, e ela est\u00e1 no outro hemisf\u00e9rio, na Austr\u00e1lia. E nada o impedir\u00e1 de ir ao encontro dela. Nessa cruzada por um mundo p\u00f3s-masculino, homem e macaco descobrir\u00e3o qu\u00e3o valiosos se tornaram',
          publishing_date: new Date('2016-07-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '72.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 65,
          isbn: '9788583681809',
          title: 'Y: O \u00daltimo Homem',
          edition: '3',
          pages: 320,
          description:
            'Em 2002 a Terra mudou para sempre. Todas as criaturas com um cromossomo Y morreram instantaneamente ao redor do globo. Com a perda de mais da metade da popula\u00e7\u00e3o, a sociedade est\u00e1 \u00e0 beira do colapso e cabe \u00e0s mulheres o fardo de juntar os peda\u00e7os e tentar manter nossa civiliza\u00e7\u00e3o. Mas esse \u201cgeneroc\u00eddio\u201d n\u00e3o foi t\u00e3o completo assim. Por alguma misteriosa raz\u00e3o, Yorick e seu macaco de estima\u00e7\u00e3o foram poupados do exterm\u00ednio. Do dia para a noite, esse desconhecido de vinte e poucos anos virou a pessoa mais importante do planeta e a chave para decifrar o mist\u00e9rio que varreu o sexo masculino do mapa. S\u00f3 que para ele a pessoa mais importante do planeta \u00e9 sua namorada, e ela est\u00e1 no outro hemisf\u00e9rio, na Austr\u00e1lia, e nada o impedir\u00e1 de ir ao encontro dela. Mas com um oceano inteiro de dist\u00e2ncia entre os dois, as chances de um reencontro est\u00e3o diminuindo \u2013 e novas amea\u00e7as chegam de todos os lados.',
          publishing_date: new Date('2017-04-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '98.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 66,
          isbn: '9788575326367',
          title: 'Saga',
          edition: '1',
          pages: 168,
          description:
            "Saga'' \u00e9 uma hist\u00f3ria em quadrinhos no melhor estilo space opera e com um toque de fantasia criada e escrita por Brian K. Vaughan e ilustrada por Fiona Staples. Publicada originalmente como uma revista mensal pela Image Comics, a s\u00e9rie \u00e9 fortemente influenciada por Star Wars, Flash Gordon e em ideias concebidas pelo pr\u00f3prio Vaughan quando ainda era crian\u00e7a (o autor revelou que a base da hist\u00f3ria foi criada durante as aulas de Matem\u00e1tica, que ele odiava!). Frequentemente descrita pela cr\u00edtica especializada como um \u201cencontro entre Star Wars e A Guerra dos Tronos\u201d, ''Saga'' nos conta a hist\u00f3ria de Alana e Marko, dois soldados em lados opostos numa longa e devastadora guerra intergal\u00e1ctica que se apaixonam e lutam para garantir que Hazel, sua filha rec\u00e9m-nascida, continue viva. Mas \u00e9 claro que isso n\u00e3o ser\u00e1 nada f\u00e1cil... Curiosamente, a hist\u00f3ria \u00e9 narrada pelo beb\u00ea!",
          publishing_date: new Date('2014-11-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '59.90',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 67,
          isbn: '9788575326183',
          title: 'Saga',
          edition: '2',
          pages: 168,
          description:
            'A rec\u00e9m-nascida Hazel j\u00e1 sobreviveu a assassinos mort\u00edferos, ex\u00e9rcitos enfurecidos, fantasmas e monstruosidades alien\u00edgenas, mas \u00e9 na vastid\u00e3o fria e escura do espa\u00e7o que a garotinha ir\u00e1 enfrentar o maior desafio da fam\u00edlia: seus av\u00f3s paternos! Bem... isso e mais algumas surpresinhas que voc\u00ea ir\u00e1 descobrir no decorrer do livro... Nas p\u00e1ginas belamente ilustradas por Fiona Staples, desvendaremos mais segredos sobre o Pr\u00edncipe Rob\u00f4, O Querer, a Gata da Mentira, e, \u00e9 claro, Alana e Marko, tudo numa trama bem engendrada por Brian K. Vaughan, um dos escritores de quadrinhos mais conceituados dos \u00faltimos tempos!',
          publishing_date: new Date('2015-12-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '65.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 68,
          isbn: '9788575326398',
          title: 'Saga',
          edition: '3',
          pages: 152,
          description:
            'Terceiro volume da multipremiada s\u00e9rie em quadrinhos que tem arrebatado leitores em todo o mundo, tornando-se um dos maiores fen\u00f4menos dessa m\u00eddia dos \u00faltimos tempos. Nesse tomo, os pais de primeira viagem, Marko e Alana, v\u00e3o at\u00e9 um mundo alien\u00edgena para encontrar seu autor preferido, enquanto seus perseguidores se aproximam cada vez mais.',
          publishing_date: new Date('2016-11-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '65.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 69,
          isbn: '9788575326473',
          title: 'Saga',
          edition: '4',
          pages: 152,
          description:
            'Quando eles chegam a um novo e estranho planeta e se deparam com outros protagonistas, a pequena Hazel j\u00e1 \u00e9 uma crian\u00e7a que sabe andar, enquanto os seus desafortunados pais, Marko e Alana, se esfor\u00e7am para se manter em p\u00e9. Enquanto Hazel come\u00e7a a pronunciar suas primeiras palavras, seus jovens pais passam por algumas crises no casamento. Alana torna-se usu\u00e1ria de uma droga do momento e Marko d\u00e1 in\u00edcio a um relacionamento extraconjugal. Mas os problemas n\u00e3o param por a\u00ed.',
          publishing_date: new Date('2017-01-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '65.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 70,
          isbn: '9788575326541',
          title: 'Saga',
          edition: '5',
          pages: 152,
          description:
            'Nesse novo volume da s\u00e9rie, m\u00faltiplas hist\u00f3rias colidem numa emocionante aventura por todo o cosmo. Enquanto Gwendolyn, Sophie, a Gata da Mentira e A M\u00e1cula, arriscam suas vidas na procura de uma cura para O Querer, Marko faz uma inc\u00f4moda alian\u00e7a com o Pr\u00edncipe Rob\u00f4 IV para ajud\u00e1-lo a encontrar seu filho raptado, que est\u00e1 preso num estranho mundo com novos e terr\u00edveis inimigos.',
          publishing_date: new Date('2017-06-01'),
          format: 'Americano (17 x 26 cm)\nColorido/Capa dura',
          price: '69.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 71,
          isbn: '9788573516050',
          title: 'terra x',
          edition: null,
          pages: 476,
          description:
            'Grandiosos \u00e9picos n\u00e3o costumam surgir com frequ\u00eancia. Hist\u00f3rias que ampliam os horizontes e obrigam o leitor a pensar. Hist\u00f3rias t\u00e3o poderosas em suas mensagens e t\u00e3o extraordin\u00e1rias em suas escalas, que os crit\u00e9rios pelos quais tais contos s\u00e3o normalmente julgados s\u00e3o completamente reformulados. Idealizada pelo consagrado ilustrador Alex Ross, Terra X \u00e9 assim. Junto do roteirista Jim Krueger e do artista John Paul Leon, Ross traz novo f\u00f4lego e acrescenta espetaculares novos detalhes a cada faceta da mitologia dos her\u00f3is e vil\u00f5es da Casa das Ideias. A obra explora todo o Universo Marvel, de suas ra\u00edzes em seu humilde surgimento, at\u00e9 o \u00e1pice de seu fabuloso potencial. Em um futuro alternativo dist\u00f3pico e inquietante, praticamente todos os habitantes da Terra desenvolveram habilidades sobre-humanas. Resta saber como esse novo status quo afeta os antigos her\u00f3is e a vida em todo o planeta.',
          publishing_date: new Date('2017-09-01'),
          format: '(13,5 x 20 cm)\nPreto e branco/Lombada quadrada',
          price: '70.00',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 72,
          isbn: '9788573514070',
          title: 'Os Maiores Super-Her\u00f3is do Mundo',
          edition: null,
          pages: 400,
          description:
            'A DC Comics n\u00e3o \u00e9 chamada de Editora das Lendas \u00e0 toa. Figuras como Superman, Batman, Mulher-Maravilha, Flash e Lanterna Verde s\u00e3o h\u00e1 d\u00e9cada mais do que simples personagens de HQs; s\u00e3o verdadeiros \u00edcones do imagin\u00e1rio popular mundial. Mas como lendas se comportam em suas vidas normais? Quais quest\u00f5es perpassam sua mente quando n\u00e3o est\u00e3o salvando o planeta da destrui\u00e7\u00e3o? S\u00e3o essas quest\u00f5es que os incompar\u00e1veis Paul Dini',
          publishing_date: new Date('2017-08-01'),
          format: '(23 x 30 cm)\nColorido/Capa dura',
          price: '93.30',
          thumbnail: null,
          total_rating: 0,
          total_favorites: 0,
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },
  down: queryInterface => {
    return queryInterface.bulkDelete('books', null, {});
  },
};
